[tox]
envlist =
    readme-py311,
    docs-py311,
    py311-django{4,5},
    py312-django{4,5},
    py313-django{5,6},
    py314-django{5,6},

[gh-actions]
python =
    3.11: py311, restlint
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
usedevelop = true
setenv =
    DJANGO_SETTINGS_MODULE = tests.settings
    PYTHONPATH = {toxinidir}
deps =
    -rtests/requirements.txt
    django4: Django>=4.0,<5.0
    django5: Django>=5.0,<6.0
    django6: Django>=6.0,<7.0
commands =
    pytest {posargs:tests}

[testenv:docs-py311]
deps =
    sphinx
commands =
    docs: sphinx-build -b html -d {envtmpdir}/doctrees docs {envtmpdir}/html

[testenv:readme-py311]
deps =
    setuptools
    twine
    readme_renderer[md]
commands =
    python setup.py sdist
    twine check dist/*

