[tox]
envlist =
    readme-py311,
    docs-py311,
    py311-django{4,50,51,52},
    py312-django{4,50,51,52},
    py313-django{51,52,60},
    py314-django{51,52,60},

[gh-actions]
python =
    3.11: py311, restlint
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
usedevelop = true
setenv =
    DJANGO_SETTINGS_MODULE = tests.settings
    PYTHONPATH = {toxinidir}
deps =
    -rtests/requirements.txt
    django4: Django>=4.0,<5.0
    django50: Django>=5.0,<5.1
    django51: Django>=5.1,<5.2
    django52: Django>=5.2,<6.0
    django60: Django>=6.0,<7.0
commands =
    pytest {posargs:tests}

[testenv:docs-py311]
deps =
    sphinx
commands =
    docs: sphinx-build -b html -d {envtmpdir}/doctrees docs {envtmpdir}/html

[testenv:readme-py311]
deps =
    setuptools
    twine
    readme_renderer[md]
commands =
    python setup.py sdist
    twine check dist/*

